// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urtuslaixqsvgkeqwntk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVydHVzbGFpeHFzdmdrZXF3bnRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDU3NTIsImV4cCI6MjA3NDIyMTc1Mn0.RO7nAcsU7W_jhZ9E4srh3eSiPuM7gHgamNgCCgtblPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});